import { useState } from 'react';
import './ControlButtons.css';
import { sendCommand, saveFlightPlan } from '../../services/MockAPI';
import { useDroneStore } from '../../store';

function ControlButtons() {

  const appMode = useDroneStore((state) => state.appMode);
  const setAppMode = useDroneStore((state) => state.setAppMode);
  const toggleStoreLogs = useDroneStore((state) => state.toggleStoreLogs);
  const storeLog = useDroneStore((state) => state.settings.system.storeLog);
  const activeWaypoints = useDroneStore((state) => state.activeWaypoints);
  const clearWaypoints = useDroneStore((state) => state.clearWaypoints);
  const saveFullFlightPlan = useDroneStore((state) => state.saveFullFlightPlan);
  
  const [planName, setPlanName] = useState("My New Plan");

  const handleCommand = async (commandName) => {
    console.log(`Attempting to send command: ${commandName}`);
    try {
      switch(commandName) {
        case "Start/End Logging":
          toggleStoreLogs();
          console.log("Log storing toggled.");
          break;

        case "New Waypoint":
          const newMode = appMode === 'adding_waypoint' ? 'idle' : 'adding_waypoint';
          setAppMode(newMode);
          console.log(`App mode set to: ${newMode}`);
          return;

        default:
          const response = await sendCommand(commandName);
          console.log(`[Mock API] response for ${commandName}:`, response);
          alert(response.message);

      }
    } catch (error) {
      console.error(`Error sending command ${commandName}:`, error);
      alert(`Failed to send command ${commandName}.`);
    }
  };

  const handleAddWaypoint = () => {
    if (appMode !== 'adding_waypoint') {
      setAppMode('adding_waypoint'); // Set mode to add a waypoint
    }
    else {
      setAppMode('idle')
    }
    // MapView will handle the rest
  };

  const handleSavePlan = async () => {
    const name = prompt("Enter a name for your flight plan:", planName);
    
    if (name) {
      setPlanName(name);
      const planData = {
        name: name,
        waypoints: activeWaypoints
      };
      
      try {
        const response = await saveFlightPlan(planData);
        alert(response.message);

        // Use the response from the backend to save in Zustrand store
        const savedPlanSummary = {
            id: response.data.id,
            name: response.data.name,
            waypointCount: response.data.waypoints.length,
            lastModified: new Date().toISOString()
        };

        // Use the drone store as a temporary database
        const fullPlanData = {
          id: response.data.id, // The ID generated by the mock API
          name: response.data.name,
          description: "Created in editor",
          lastModified: new Date().toISOString(),
          waypoints: response.data.waypoints // The actual waypoints
        };

        saveFullFlightPlan(fullPlanData);
        
        // Add it to the global store list
        // saveFullFlightPlan(savedPlanSummary);

        // Go back to idle mode.
        setAppMode('idle');
        // clearWaypoints();
      } catch (error) {
        alert(`Failed to save plan: ${error}`);
      }
    }
  };

  const handleCancelPlan = () => {
    if (window.confirm("Are you sure? All unsaved waypoints will be lost.")) {
      setAppMode('idle');
      clearWaypoints();
    }
  };


  if (appMode === 'PLANNING' || appMode === 'adding_waypoint') {
    return (
      <div className="control-buttons planning">
        <button 
          className={appMode === 'adding_waypoint' ? 'active' : ''}
          onClick={handleAddWaypoint}
        >
          Add Waypoint
        </button>
        <button className="btn-save" onClick={handleSavePlan}>
          Save Plan
        </button>
        <button className="btn-cancel" onClick={handleCancelPlan}>
          Cancel
        </button>
      </div>
    );
  }

  return (
    <div className="control-buttons idle">
      <button 
        className={storeLog === true ? 'active' : ''}
        onClick={() => handleCommand('Start/End Logging')}
      >
        Start/End Logging
      </button>
      
      <button onClick={() => handleCommand('Hover')}>Hover</button>
      <button onClick={() => handleCommand('Land')}>Land</button>
      <button className="home-button" onClick={() => handleCommand('Return to Home')}>🏠</button>
    </div>
  );

  // return (
  //   <div className="control-buttons">
  //     <button 
  //       className={storeLog === true ? 'active' : ''}
  //       onClick={() => handleCommand('Start/End Logging')}
  //     >
  //       Start/End Logging
  //     </button>

  //     <button 
  //       className={appMode === 'adding_waypoint' ? 'active' : ''}
  //       onClick={() => handleCommand('New Waypoint')}
  //     >
  //       New Waypoint
  //     </button>
      
  //     <button onClick={() => handleCommand('Hover')}>Hover</button>
  //     <button onClick={() => handleCommand('Land')}>Land</button>
  //     <button className="home-button" onClick={() => handleCommand('Return to Home')}>🏠</button>
  //   </div>
  // );
}

export default ControlButtons;
